/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retailordermanagementsystem;

/**
 *
 * @author Maxine
 */
public class AddSupplier extends javax.swing.JPanel {

    /**
     * Creates new form AddSupplier
     */
    public AddSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelSupplierName = new javax.swing.JLabel();
        labelFirstName1 = new javax.swing.JLabel();
        labelLastName1 = new javax.swing.JLabel();
        labelSupPhone = new javax.swing.JLabel();
        labelSupState = new javax.swing.JLabel();
        labelSupRemarks = new javax.swing.JLabel();
        textSupRemarks = new javax.swing.JTextField();
        textSupStreet = new javax.swing.JTextField();
        textSupPhone = new javax.swing.JTextField();
        textPICFirstName = new javax.swing.JTextField();
        textPICLastName = new javax.swing.JTextField();
        textSupplierName = new javax.swing.JTextField();
        buttonCancel = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelSupEmail = new javax.swing.JLabel();
        textSupEmail = new javax.swing.JTextField();
        labelSupStreet = new javax.swing.JLabel();
        labelSupCity = new javax.swing.JLabel();
        textSupCity = new javax.swing.JTextField();
        labelSupPostcode = new javax.swing.JLabel();
        textSupPostcode = new javax.swing.JTextField();
        comboSupState = new javax.swing.JComboBox<>();

        labelSupplierName.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        labelSupplierName.setText("Supplier Name");

        labelFirstName1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        labelFirstName1.setText("PIC First Name");

        labelLastName1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        labelLastName1.setText("PIC Last Name");

        labelSupPhone.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        labelSupPhone.setText("Phone");

        labelSupState.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        labelSupState.setText("State");

        labelSupRemarks.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        labelSupRemarks.setText("Remarks");

        textSupRemarks.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        textSupStreet.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        textSupStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSupStreetActionPerformed(evt);
            }
        });

        textSupPhone.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        textPICFirstName.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        textPICLastName.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        textSupplierName.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        buttonCancel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        buttonCancel.setText("Cancel");
        buttonCancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonSave.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        buttonSave.setText("Save");
        buttonSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        labelTitle.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("New Supplier");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelSupEmail.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        labelSupEmail.setText("Email");

        textSupEmail.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        textSupEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSupEmailActionPerformed(evt);
            }
        });

        labelSupStreet.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        labelSupStreet.setText("Street");

        labelSupCity.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        labelSupCity.setText("City");

        textSupCity.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        textSupCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSupCityActionPerformed(evt);
            }
        });

        labelSupPostcode.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        labelSupPostcode.setText("Postcode");

        textSupPostcode.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        textSupPostcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSupPostcodeActionPerformed(evt);
            }
        });

        comboSupState.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboSupState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select State>", "Kuala Lumpur", "Selangor", "Putrajaya", "Labuan", "Perlis", "Kedah", "Terengganu", "Pahang", "Perak", "Kelantan", "Penang", "Selangor", "Negeri Sembilan", "Johor", "Malacca", "Sabah", "Sarawak" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelSupRemarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSupPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelFirstName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSupplierName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelLastName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSupEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSupStreet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSupCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSupState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSupPostcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textSupplierName)
                            .addComponent(textPICFirstName)
                            .addComponent(textPICLastName)
                            .addComponent(textSupPhone)
                            .addComponent(textSupStreet)
                            .addComponent(textSupEmail)
                            .addComponent(textSupCity)
                            .addComponent(textSupPostcode)
                            .addComponent(comboSupState, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(textSupRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSupplierName)
                    .addComponent(textSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstName1)
                    .addComponent(textPICFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLastName1)
                    .addComponent(textPICLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSupPhone)
                    .addComponent(textSupPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSupEmail)
                    .addComponent(textSupEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSupStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSupStreet))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSupCity)
                    .addComponent(textSupCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSupPostcode)
                    .addComponent(textSupPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSupState)
                    .addComponent(comboSupState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSupRemarks)
                    .addComponent(textSupRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textSupStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSupStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSupStreetActionPerformed

    private void textSupEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSupEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSupEmailActionPerformed

    private void textSupCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSupCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSupCityActionPerformed

    private void textSupPostcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSupPostcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSupPostcodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox<String> comboSupState;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelFirstName1;
    private javax.swing.JLabel labelLastName1;
    private javax.swing.JLabel labelSupCity;
    private javax.swing.JLabel labelSupEmail;
    private javax.swing.JLabel labelSupPhone;
    private javax.swing.JLabel labelSupPostcode;
    private javax.swing.JLabel labelSupRemarks;
    private javax.swing.JLabel labelSupState;
    private javax.swing.JLabel labelSupStreet;
    private javax.swing.JLabel labelSupplierName;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField textPICFirstName;
    private javax.swing.JTextField textPICLastName;
    private javax.swing.JTextField textSupCity;
    private javax.swing.JTextField textSupEmail;
    private javax.swing.JTextField textSupPhone;
    private javax.swing.JTextField textSupPostcode;
    private javax.swing.JTextField textSupRemarks;
    private javax.swing.JTextField textSupStreet;
    private javax.swing.JTextField textSupplierName;
    // End of variables declaration//GEN-END:variables
}
