/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retailordermanagementsystem;

/**
 *
 * @author Maxine
 */
public class AdminOrderList extends javax.swing.JPanel {

    /**
     * Creates new form AdProductList
     */
    public AdminOrderList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrderList = new javax.swing.JTable();
        labelTitle = new javax.swing.JLabel();
        buttonOrderCompleted = new javax.swing.JButton();
        buttonOrderCancelled = new javax.swing.JButton();
        buttonOrderWaiting = new javax.swing.JButton();
        buttonAddOrder = new javax.swing.JButton();
        buttonEditOrder = new javax.swing.JButton();
        buttonDeleteOrder = new javax.swing.JButton();

        tableOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Customer ID", "Address", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableOrderList);

        labelTitle.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        labelTitle.setText("Order List");
        labelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonOrderCompleted.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        buttonOrderCompleted.setText("Completed");

        buttonOrderCancelled.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        buttonOrderCancelled.setText("Cancelled");
        buttonOrderCancelled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrderCancelledActionPerformed(evt);
            }
        });

        buttonOrderWaiting.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        buttonOrderWaiting.setText("Waiting");
        buttonOrderWaiting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrderWaitingActionPerformed(evt);
            }
        });

        buttonAddOrder.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        buttonAddOrder.setText("Add");
        buttonAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddOrderActionPerformed(evt);
            }
        });

        buttonEditOrder.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        buttonEditOrder.setText("Edit");
        buttonEditOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditOrderActionPerformed(evt);
            }
        });

        buttonDeleteOrder.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        buttonDeleteOrder.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonOrderWaiting)
                .addGap(18, 18, 18)
                .addComponent(buttonOrderCancelled)
                .addGap(18, 18, 18)
                .addComponent(buttonOrderCompleted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAddOrder)
                .addGap(18, 18, 18)
                .addComponent(buttonEditOrder)
                .addGap(18, 18, 18)
                .addComponent(buttonDeleteOrder)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonAddOrder)
                        .addComponent(buttonDeleteOrder)
                        .addComponent(buttonEditOrder)
                        .addComponent(buttonOrderCompleted)
                        .addComponent(buttonOrderCancelled)
                        .addComponent(buttonOrderWaiting))
                    .addComponent(labelTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOrderCancelledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrderCancelledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOrderCancelledActionPerformed

    private void buttonEditOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditOrderActionPerformed

    private void buttonAddOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddOrderActionPerformed

    private void buttonOrderWaitingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrderWaitingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOrderWaitingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddOrder;
    private javax.swing.JButton buttonDeleteOrder;
    private javax.swing.JButton buttonEditOrder;
    private javax.swing.JButton buttonOrderCancelled;
    private javax.swing.JButton buttonOrderCompleted;
    private javax.swing.JButton buttonOrderWaiting;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTable tableOrderList;
    // End of variables declaration//GEN-END:variables
}
